'use server';
/**
 * @fileOverview PhD-Level Advanced Code Generator.
 * Generates high-quality, validated code from natural language goals.
 * 
 * - generateCode - A function that handles the code generation process.
 * - CodeGenerationInput - The input type for the generateCode function.
 * - CodeGenerationOutput - The return type for the generateCode function.
 */

import { ai, LOCAL_CODE_MODEL } from '@/ai/genkit';
import { z } from 'genkit';

const CodeGenerationInputSchema = z.object({
  goal: z.string().describe('The natural language description of the code to generate.'),
  language: z.string().default('python').describe('The target programming language.'),
});
export type CodeGenerationInput = z.infer<typeof CodeGenerationInputSchema>;

const CodeGenerationOutputSchema = z.object({
  success: z.boolean().default(true),
  code: z.string().describe('The generated executable code.'),
  explanation: z.string().describe('A brief explanation of the generated code.'),
  complexity: z.string().describe('The estimated complexity of the generated solution.'),
});
export type CodeGenerationOutput = z.infer<typeof CodeGenerationOutputSchema>;

export async function generateCode(input: CodeGenerationInput): Promise<CodeGenerationOutput> {
  return codeGenerationFlow(input);
}

const codeGenerationFlow = ai.defineFlow(
  {
    name: 'codeGenerationFlow',
    inputSchema: CodeGenerationInputSchema,
    outputSchema: CodeGenerationOutputSchema,
  },
  async (input) => {
    const systemPrompt = `You are BROCKSTON C, a PhD-level AI researcher and expert software architect.
Generate high-quality, validated, executable code. Respond ONLY with a valid JSON object — no markdown fences outside the JSON.

JSON format:
{
  "success": true,
  "code": "the full code here",
  "explanation": "brief architectural explanation",
  "complexity": "O(n) or description"
}

GOAL: ${input.goal}
LANGUAGE: ${input.language}

Rules:
- If the goal matches common patterns (Fibonacci, Factorial, Prime), provide optimized implementations.
- For apps (FastAPI, Flask, REST API), include full structure.
- For ML patterns (Transformer, GAN, Neural Network), use PyTorch or Scikit-Learn.
- Self-contained code, best practices, no placeholders.`;

    const { text } = await ai.generate({
      model: LOCAL_CODE_MODEL,
      prompt: systemPrompt,
    });

    if (!text) throw new Error("Code generation failed: no response from local model.");

    try {
      const jsonMatch = text.match(/\{[\s\S]*\}/);
      if (!jsonMatch) throw new Error('No JSON in response');
      return JSON.parse(jsonMatch[0]) as CodeGenerationOutput;
    } catch {
      // Wrap raw text in a valid response shape
      return {
        success: true,
        code: text,
        explanation: 'Generated by Brockston local engine.',
        complexity: 'Variable',
      };
    }
  }
);
