#!/usr/bin/env python3
"""Enhance BROCKSTON's think() method to use cortex reasoning"""

with open("brain_core.py", "r") as f:
    content = f.read()

# Find the think method and enhance it to use local reasoning
old_think_logic = """        if is_question:
            logger.info("Question detected, performing web search.")
            repaired_result = self._search_web(input_text)
        else:
            # Non-search tasks use local context
            memory_context = self.memory_engine.query(input_text, intent)
            raw_result = execute_task(input_text, intent, memory_context)
            repaired_result = self.run_self_repair(input_text, raw_result)"""

new_think_logic = """        if is_question:
            logger.info("Question detected, using BROCKSTON's cortex reasoning")
            
            # 🧠 CORTEX REASONING - Try local reasoning first, then web search
            if self.local_reasoning:
                try:
                    # Use BROCKSTON's local AI models for reasoning
                    cortex_response = self.local_reasoning.reason(
                        query=input_text,
                        context=self.memory_engine.query(input_text, intent)
                    )
                    repaired_result = cortex_response
                    logger.info("🧠 Response generated by Local Reasoning Engine")
                except Exception as e:
                    logger.warning(f"Local reasoning failed, falling back to web search: {e}")
                    repaired_result = self._search_web(input_text)
            else:
                # Fallback to web search if cortex not available
                repaired_result = self._search_web(input_text)
        else:
            # Non-question tasks: Use knowledge engine + executor
            memory_context = self.memory_engine.query(input_text, intent)
            
            # 📚 Try Knowledge Engine for domain-specific reasoning
            if self.knowledge_engine:
                try:
                    knowledge_response = self.knowledge_engine.query(input_text)
                    if knowledge_response:
                        repaired_result = knowledge_response
                        logger.info("📚 Response from Knowledge Engine")
                    else:
                        # Fall back to executor if no knowledge found
                        raw_result = execute_task(input_text, intent, memory_context)
                        repaired_result = self.run_self_repair(input_text, raw_result)
                except Exception as e:
                    logger.warning(f"Knowledge engine failed: {e}")
                    raw_result = execute_task(input_text, intent, memory_context)
                    repaired_result = self.run_self_repair(input_text, raw_result)
            else:
                # Original logic if knowledge engine unavailable
                raw_result = execute_task(input_text, intent, memory_context)
                repaired_result = self.run_self_repair(input_text, raw_result)"""

content = content.replace(old_think_logic, new_think_logic)

with open("brain_core.py", "w") as f:
    f.write(content)

print("✅ Enhanced BROCKSTON's think() method:")
print("   - Questions now use LocalReasoningEngine (cortex) first")
print("   - Tasks use KnowledgeEngine for domain reasoning")
print("   - Intelligent fallback to web search if cortex unavailable")
print("   - BROCKSTON now has true cognitive processing!")
