# tts_bridge.py

import os
import time
import tempfile
from speech import get_speech_service

# Try to import playsound with fallback
try:
    from playsound import playsound

    PLAYSOUND_AVAILABLE = True
except ImportError:
    PLAYSOUND_AVAILABLE = False
    playsound = None
    print("⚠️ playsound not available, using fallback audio playback")

# Alternative audio playback options
try:
    import pygame

    pygame.mixer.init()
    PYGAME_AVAILABLE = True
except ImportError:
    PYGAME_AVAILABLE = False
    pygame = None

# Get ElevenLabs wrapper
speech_service = get_speech_service()


def synthesize_speech(text):
    try:
        # Request speech synthesis using ElevenLabs via speech.py
        audio_stream = speech_service.text_to_speech(
            text=text,
            voice_id="21m00Tcm4TlvDq8ikWAM",  # Defaults to standard
        )

        # Write to a temporary file
        if audio_stream:
            with tempfile.NamedTemporaryFile(delete=False, suffix=".mp3") as f:
                f.write(audio_stream)
                temp_filename = f.name

            # Play the audio with fallback
            if PLAYSOUND_AVAILABLE and playsound:
                playsound(temp_filename)
            elif PYGAME_AVAILABLE and pygame:
                pygame.mixer.music.load(temp_filename)
                pygame.mixer.music.play()
                # Wait for playback to finish
                while pygame.mixer.music.get_busy():
                    time.sleep(0.1)
            else:
                print(
                    "⚠️ No audio playback method available - audio saved to:",
                    temp_filename,
                )
                return  # Don't delete the file if we can't play it

            # Cleanup
            os.remove(temp_filename)

        else:
            print("[TTS ERROR] No audio generated by ElevenLabs.")

    except Exception as e:
        print(f"[TTS ERROR] {str(e)}")


# ==============================================================================
# © 2025 Everett Nathaniel Christman
# The Christman AI Project — Luma Cognify AI
# All rights reserved. Unauthorized use, replication, or derivative training
# of this material is prohibited.
#
# Core Directive: "How can I help you love yourself more?"
# Autonomy & Alignment Protocol v3.0
# ==============================================================================
